#include "header.h"

int getCode(char* wrd) {
  int i;
  int t;
  if (wrd[0] >= '0' && wrd[0] <= '9') return atoi(wrd);
  if (wrd[0] == '-' && wrd[1] >= '0' && wrd[1] <= '9') return atoi(wrd);
  if (strcasecmp(wrd,"INROOM?") == 0) return CMD_IN_ROOM;
  if (strcasecmp(wrd,"TELEPORT") == 0) return CMD_TELEPORT;
  if (strcasecmp(wrd,"NOTINROOM?") == 0) return CMD_NOT_IN_ROOM;
  if (strcasecmp(wrd,"SAY")    == 0) return CMD_SAY;
  if (strcasecmp(wrd,"ADDSCORE") == 0) return CMD_ADD_SCORE;
  if (strcasecmp(wrd,"SUBSCORE") == 0) return CMD_SUB_SCORE;
  if (strcasecmp(wrd,"TRUE")   == 0) return CMD_TRUE;
  if (strcasecmp(wrd,"FALSE")  == 0) return CMD_FALSE;
  if (strcasecmp(wrd,"ELSE")   == 0) return CMD_ELSE;
  if (strcasecmp(wrd,"DIE")    == 0) return CMD_DIE;
  if (strcasecmp(wrd,"WIN")    == 0) return CMD_WIN;
  if (strcasecmp(wrd,"LOSE")   == 0) return CMD_LOSE;
  if (strcasecmp(wrd,"MORE")   == 0) return CMD_MORE;
  if (strcasecmp(wrd,"CARRYING?") == 0) return CMD_CARRYING;
  if (strcasecmp(wrd,"NOTCARRYING?") == 0) return CMD_NOT_CARRYING;
  if (strcasecmp(wrd,"FLAGSET?")  == 0) return CMD_FLAG_SET;
  if (strcasecmp(wrd,"FLAGRESET?") == 0) return CMD_FLAG_RESET;
  if (strcasecmp(wrd,"SETFLAG")  == 0) return CMD_SET_FLAG;
  if (strcasecmp(wrd,"RESETFLAG") == 0) return CMD_RESET_FLAG;
  if (strcasecmp(wrd,"ITEMINROOM?") == 0) return CMD_OBJECT_IN_ROOM;
  if (strcasecmp(wrd,"ITEMNOTINROOM?") == 0) return CMD_OBJECT_NOT_IN_ROOM;
  if (strcasecmp(wrd,"PLACEITEM") == 0) return CMD_PLACE_OBJECT;
  if (strcasecmp(wrd,"TAKEITEM") == 0) return CMD_TAKE_OBJECT;
  if (strcasecmp(wrd,"DROPITEM") == 0) return CMD_DROP_OBJECT;
  if (strcasecmp(wrd,"IF") == 0) return CMD_IF;
  if (strcasecmp(wrd,"+") == 0) return CMD_ADD;
  if (strcasecmp(wrd,"-") == 0) return CMD_SUB;
  if (strcasecmp(wrd,"*") == 0) return CMD_MUL;
  if (strcasecmp(wrd,"/") == 0) return CMD_DIV;
  if (strcasecmp(wrd,"dup") == 0) return CMD_DUP;
  if (strcasecmp(wrd,"drop") == 0) return CMD_DROP;
  if (strcasecmp(wrd,"swap") == 0) return CMD_SWAP;
  if (strcasecmp(wrd,"set") == 0) return CMD_SET;
  if (strcasecmp(wrd,"get") == 0) return CMD_GET;
  if (strcasecmp(wrd,"!") == 0) return CMD_SET;
  if (strcasecmp(wrd,"@") == 0) return CMD_GET;
  if (strcasecmp(wrd,"=") == 0) return CMD_EQ;
  if (strcasecmp(wrd,"<>") == 0) return CMD_NE;
  if (strcasecmp(wrd,">") == 0) return CMD_GT;
  if (strcasecmp(wrd,"<") == 0) return CMD_LT;
  if (strcasecmp(wrd,">=") == 0) return CMD_GE;
  if (strcasecmp(wrd,"<=") == 0) return CMD_LE;
  if (strcasecmp(wrd,"random") == 0) return CMD_RANDOM;
  if (strcasecmp(wrd,".") == 0) return CMD_DOT;
  if (strcasecmp(wrd,"cr") == 0) return CMD_CR;
  if (strcasecmp(wrd,"nsay") == 0) return CMD_NSAY;
  if (strcasecmp(wrd,"enteredfrom?") == 0) return CMD_ENTERED;
  if (strcasecmp(wrd,"goingwest?") == 0) return CMD_GOING_WEST;
  if (strcasecmp(wrd,"goingeast?") == 0) return CMD_GOING_EAST;
  if (strcasecmp(wrd,"goingnorth?") == 0) return CMD_GOING_NORTH;
  if (strcasecmp(wrd,"goingsouth?") == 0) return CMD_GOING_SOUTH;
  if (strcasecmp(wrd,"goingup?") == 0) return CMD_GOING_UP;
  if (strcasecmp(wrd,"goingdown?") == 0) return CMD_GOING_DOWN;
  if (strcasecmp(wrd,"currentroom") == 0) return CMD_CURRENT_ROOM;
  if (strcasecmp(wrd,"removeitem") == 0) return CMD_REMOVE_ITEM;
  if (strcasecmp(wrd,"then") == 0) return CMD_THEN;
  if (strcasecmp(wrd,"over") == 0) return CMD_OVER;
  if (strcasecmp(wrd,"rot") == 0) return CMD_ROT;
  if (strcasecmp(wrd,"-rot") == 0) return CMD_MROT;
  if (strcasecmp(wrd,"and") == 0) return CMD_AND;
  if (strcasecmp(wrd,"or") == 0) return CMD_OR;
  if (strcasecmp(wrd,"xor") == 0) return CMD_XOR;
  if (strcasecmp(wrd,"pick") == 0) return CMD_PICK;
  if (strcasecmp(wrd,"do") == 0) return CMD_DO;
  if (strcasecmp(wrd,"i") == 0) return CMD_I;
  if (strcasecmp(wrd,"roomdesc") == 0) return CMD_ROOM_DESC;
  if (strcasecmp(wrd,"loop") == 0) return CMD_LOOP;
  if (strcasecmp(wrd,"spaces") == 0) return CMD_SPACES;
  if (strcasecmp(wrd,"location") ==0 ) return CMD_LOCATION;
  if (strcasecmp(wrd,"extractitem") == 0) return CMD_EXTRACT;
  if (strcasecmp(wrd,"score") == 0) return CMD_SCORE;
  if (strcasecmp(wrd,"weight") == 0) return CMD_WEIGHT;
  if (strcasecmp(wrd,"geteast") == 0) return CMD_GET_EAST;
  if (strcasecmp(wrd,"getwest") == 0) return CMD_GET_WEST;
  if (strcasecmp(wrd,"getnorth") == 0) return CMD_GET_NORTH;
  if (strcasecmp(wrd,"getsouth") == 0) return CMD_GET_SOUTH;
  if (strcasecmp(wrd,"getup") == 0) return CMD_GET_UP;
  if (strcasecmp(wrd,"getdown") == 0) return CMD_GET_DOWN;
  if (strcasecmp(wrd,"emit") == 0) return CMD_EMIT;
  if (strcasecmp(wrd,"not") == 0) return CMD_NOT;
  if (strcasecmp(wrd,"light") == 0) return CMD_LIGHT;
  if (strcasecmp(wrd,"light?") == 0) return CMD_HAS_LIGHT;
  if (strcasecmp(wrd,"open") == 0) return CMD_OPEN;
  if (strcasecmp(wrd,"close") == 0) return CMD_CLOSE;
  if (strcasecmp(wrd,"opened?") == 0) return CMD_OPENED;
  if (strcasecmp(wrd,"lock") == 0) return CMD_LOCK;
  if (strcasecmp(wrd,"unlock") == 0) return CMD_UNLOCK;
  if (strcasecmp(wrd,"unlock?") == 0) return CMD_UNLOCKED;
  if (strcasecmp(wrd,"turncount") == 0) return CMD_TURNCOUNT;
  if (strcasecmp(wrd,"examineitem") == 0) return CMD_EXAMINEITEM;
  if (strcasecmp(wrd,"opendoor") == 0) return CMD_OPEN_DOOR;
  if (strcasecmp(wrd,"closedoor") == 0) return CMD_CLOSE_DOOR;
  if (strcasecmp(wrd,"lockdoor") == 0) return CMD_LOCK_DOOR;
  if (strcasecmp(wrd,"unlockdoor") == 0) return CMD_UNLOCK_DOOR;
  if (strcasecmp(wrd,"doorlocked?") == 0) return CMD_DOOR_LOCKED;
  if (strcasecmp(wrd,"doorclosed?") == 0) return CMD_DOOR_CLOSED;
  if (strcasecmp(wrd,"invcount") == 0) return CMD_INV_COUNT;
  if (strcasecmp(wrd,"mod") == 0) return CMD_MOD;
  if (strcasecmp(wrd,"invitem") == 0) return CMD_INVITEM;
  if (strcasecmp(wrd,"describeitem") == 0) return CMD_DESC_ITEM;
  if (strcasecmp(wrd,"space") == 0) return CMD_SPACE;
  if (strcasecmp(wrd,"wearable?") == 0) return CMD_WEARABLE;
  if (strcasecmp(wrd,"wearing?") == 0) return CMD_WEARING;
  if (strcasecmp(wrd,"while") == 0) return CMD_WHILE;
  if (strcasecmp(wrd,"repeat") == 0) return CMD_REPEAT;
  if (strcasecmp(wrd,"count") == 0) return CMD_COUNT;
  if (strcasecmp(wrd,"clear") == 0) return CMD_CLEAR;
  if (strcasecmp(wrd,"begin") == 0) return CMD_BEGIN;
  if (strcasecmp(wrd,"until") == 0) return CMD_UNTIL;
  if (strcasecmp(wrd,"n.") == 0) return CMD_NDOT;
  if (strcasecmp(wrd,"stack") == 0) return CMD_STACK;
  if (strcasecmp(wrd,"abs") == 0) return CMD_ABS;
  if (strcasecmp(wrd,"sgn") == 0) return CMD_SGN;
  if (strcasecmp(wrd,"inc") == 0) return CMD_INC;
  if (strcasecmp(wrd,"++") == 0) return CMD_INC;
  if (strcasecmp(wrd,"dec") == 0) return CMD_DEC;
  if (strcasecmp(wrd,"--") == 0) return CMD_DEC;
  if (strcasecmp(wrd,"aug") == 0) return CMD_AUG;
  if (strcasecmp(wrd,"dim") == 0) return CMD_DIM;
  if (strcasecmp(wrd,"chs") == 0) return CMD_CHS;
  if (strcasecmp(wrd,"min") == 0) return CMD_MIN;
  if (strcasecmp(wrd,"max") == 0) return CMD_MAX;
  if (strcasecmp(wrd,"nmin") == 0) return CMD_NMIN;
  if (strcasecmp(wrd,"nmax") == 0) return CMD_NMAX;
  if (strcasecmp(wrd,"ndrop") == 0) return CMD_NDROP;
  if (strcasecmp(wrd,"sum") == 0) return CMD_SUM;
  if (strcasecmp(wrd,"dropuntil") == 0) return CMD_DROPUNTIL;
  if (strcasecmp(wrd,"dup2") == 0) return CMD_DUP2;
  if (strcasecmp(wrd,"swap2") == 0) return CMD_SWAP2;
  if (strcasecmp(wrd,"?") == 0) return CMD_QMARK;
  if (strcasecmp(wrd,"&") == 0) return CMD_L_AND;
  if (strcasecmp(wrd,"|") == 0) return CMD_L_OR;
  if (strcasecmp(wrd,"^") == 0) return CMD_L_XOR;
  if (strcasecmp(wrd,"~") == 0) return CMD_L_NOT;
  if (strcasecmp(wrd,"itemcount") == 0) return CMD_ITEMCOUNT;
  if (strcasecmp(wrd,"s.") == 0) return CMD_S_DOT;
  if (strcasecmp(wrd,"s?") == 0) return CMD_S_QMARK;
  if (strcasecmp(wrd,"slen") == 0) return CMD_S_LEN;
  if (strcasecmp(wrd,"sleft") == 0) return CMD_S_LEFT;
  if (strcasecmp(wrd,"scopy") == 0) return CMD_S_COPY;
  if (strcasecmp(wrd,"s+") == 0) return CMD_S_PLUS;
  if (strcasecmp(wrd,"sright") == 0) return CMD_S_RIGHT;
  if (strcasecmp(wrd,"s@") == 0) return CMD_S_AT;
  if (strcasecmp(wrd,"sget") == 0) return CMD_S_AT;
  if (strcasecmp(wrd,"s!") == 0) return CMD_S_SET;
  if (strcasecmp(wrd,"sset") == 0) return CMD_S_SET;
  if (strcasecmp(wrd,"s=") == 0) return CMD_S_EQ;
  if (strcasecmp(wrd,"s<>") == 0) return CMD_S_NE;
  if (strcasecmp(wrd,"s>") == 0) return CMD_S_GT;
  if (strcasecmp(wrd,"s<") == 0) return CMD_S_LT;
  if (strcasecmp(wrd,"s>=") == 0) return CMD_S_GE;
  if (strcasecmp(wrd,"s<=") == 0) return CMD_S_LE;
  if (strcasecmp(wrd,"sclear") == 0) return CMD_S_CLEAR;
  if (strcasecmp(wrd,"strim") == 0) return CMD_S_TRIM;
  if (strcasecmp(wrd,"slc") == 0) return CMD_S_LC;
  if (strcasecmp(wrd,"suc") == 0) return CMD_S_UC;
  if (strcasecmp(wrd,"sval") == 0) return CMD_S_VAL;
  if (strcasecmp(wrd,"sstr") == 0) return CMD_S_STR;
  if (strcasecmp(wrd,"bless") == 0) return CMD_BLESS;
  if (strcasecmp(wrd,"curse") == 0) return CMD_CURSE;
  if (strcasecmp(wrd,"cursed?") == 0) return CMD_CURSED;
  if (strcasecmp(wrd,"container?") == 0) return CMD_ISCONTAINER;
  if (strcasecmp(wrd,"contents") == 0) return CMD_CONTENTS;
  if (strcasecmp(wrd,"putinto") == 0) return CMD_PUT_INTO;
  if (strcasecmp(wrd,"takefrom") == 0) return CMD_TAKE_FROM;
  if (strcasecmp(wrd,"contains?") == 0) return CMD_CONTAINS;
  if (strcasecmp(wrd,"health") == 0) return CMD_HEALTH;
  if (strcasecmp(wrd,"health+") == 0) return CMD_HEALTH_PLUS;
  if (strcasecmp(wrd,"health-") == 0) return CMD_HEALTH_MINUS;
  if (strcasecmp(wrd,"health=") == 0) return CMD_HEALTH_EQ;
  if (strcasecmp(wrd,"linknorth") == 0) return CMD_LINK_NORTH;
  if (strcasecmp(wrd,"linksouth") == 0) return CMD_LINK_SOUTH;
  if (strcasecmp(wrd,"linkeast") == 0) return CMD_LINK_EAST;
  if (strcasecmp(wrd,"linkwest") == 0) return CMD_LINK_WEST;
  if (strcasecmp(wrd,"linkne") == 0) return CMD_LINK_NE;
  if (strcasecmp(wrd,"linknw") == 0) return CMD_LINK_NW;
  if (strcasecmp(wrd,"linkse") == 0) return CMD_LINK_SE;
  if (strcasecmp(wrd,"linksw") == 0) return CMD_LINK_SW;
  if (strcasecmp(wrd,"linkup") == 0) return CMD_LINK_UP;
  if (strcasecmp(wrd,"linkdown") == 0) return CMD_LINK_DOWN;
  for (i=0; i<numItems; i++)
    if (strcasecmp(wrd,items[i]->name) == 0) return i;
  for (i=0; i<numRooms; i++)
    if (strcasecmp(wrd,rooms[i]->name) == 0) return i;
  for (i=0; i<numFlagNames; i++)
    if (strcasecmp(wrd,flagNames[i]) == 0) return i;  
  for (i=0; i<numVarNames; i++)
    if (strcasecmp(wrd,varNames[i]) == 0) return i;  
  for (i=0; i<numSVars; i++)
    if (strcasecmp(wrd,sVarNames[i]) == 0) return i;  
  t = -1;
  for (i=0; i<numVocab; i++)
    if (strcasecmp(wrd,vocab[i]) == 0) t = i;
  for (i=0; i<numFunctions; i++) {
    if (t == functions[i]->phraseTokens[0]) return i+40000;  
    }
  for (i=0; i<numEquates; i++)
    if (strcasecmp(wrd,equates[i]) == 0) return eqValues[i];  
  return CMD_ERROR;
  }
